function csc_Y_l_m = csc_Y_l_m_series_expans(theta_set, phi_set, l, m)

% series expansion with order = 4
%
% csc_expanded = (1./theta_set) + theta_set/6 + (7/360)*(theta_set.^3);
% 
% Y_l_m_expanded = (theta_set.^(-m)).*exp(i*m*phi_set).*sqrt( (1+2*l)/pochhammer(l+1-m,2*m) ).*( ...
%     (1/(sqrt(pi)*gamma(1-m))).*(2^(-1+m)) + ...
%     ((theta_set.^2)/(sqrt(pi)*2)).*( -m*(2^(-2+m))/(3*gamma(1-m)) - (l*(l+1))*(2^(-2+m)) / gamma(2-m) ) + ...
%     ((theta_set.^4)/(sqrt(pi)*2)).*(  (2^m)*(m/480 + (m/144)*(-1 + m/2))/gamma(1-m) + m*l*(1+l)*(2^(-4+m))/(3*gamma(2-m)) + ...
%         (2^m)*( l*(1+l)/(48*gamma(2-m)) + l*(1+l)*(-1+l)*(2+l)/(32*gamma(3-m)) )) );
%     
% csc_Y_l_m = csc_expanded.*Y_l_m_expanded;
%
        
 csc_Y_l_m = (theta_set.^(-m-1)).*exp(1i*m*phi_set).*sqrt( (1+2*l)/pochhammer(l+1-m,2*m) ).*( ...
     (1./(sqrt(pi)*gamma(1-m))).*(2^(-1+m)) + ...
     (theta_set.^2).*( ((2^(-2+m))/(3*sqrt(pi)*gamma(1-m)) - ((2^(-2+m))/(sqrt(pi)*2)).*(m/(3*gamma(1-m)) + l*(l+1)/gamma(2-m)) )) + ...
     (theta_set.^4).*( (7*2^(-4+m))./(45*sqrt(pi)*gamma(1-m)) - ((2^(-2+m))./(sqrt(pi)*12)).*(m/(3*gamma(1-m)) + l*(l+1)./gamma(2-m)) + ...
                       ((2^m)./(sqrt(pi)*2)).*( (m/480 + (m/144)*(-1 + m/2))./gamma(1-m) + l*(l+1)*m./(48*gamma(2-m)) + l*(l+1)./(48*gamma(2-m)) + ...
                       l*(1+l)*(-1+l)*(2+l)./(32*gamma(3-m))) ) );
